import React from 'react';
import '../../../client/src/App.css';
import {Route, Routes} from 'react-router-dom';
import Account from './Account.jsx';
import Home from './ProtectedHome.jsx';
import Landing from './Home.jsx';
import Navigation from './Navigation.jsx';
import SignIn from './SignIn.jsx';
import SignUp from './SignUp.jsx';
import {AuthProvider} from '../context/AuthContext.jsx';
import PrivateRoute from './PrivateRoute.jsx';
